<?php 

	// Ensure uninstall source is WordPress...
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit();
}
	// Define the key used for storing options...
$tag = 'availability';
	// Buld the table name...
global $wpdb;
$table = $wpdb->prefix . $tag;
	// Remove the table if it exists...
$wpdb->query("DROP TABLE IF EXISTS $table");
	// Delete the options...
delete_option( $tag );